FORMAT: 1A

# User [/user]

## User Dictionary [/user/{user-id}/dictionary]

### Get user's dictionary [GET]

+ Response 200 (application/json)
    + Body
            {
                data: {
                    words: [
                        {
                            "dictionaryWord": "hello",
                            "partOfSpeechTag": "INTJ",
                            "languages": ["en"]
                        },
                    ]
                }
                "error": null,
                "meta": {}
            }

## Updates [PUT /user/{user-id}/dictionary]

+ Request (application/json)
    + Body

            {
                words: [
                        {
                            "dictionaryWord": "hello",
                            "partOfSpeechTag": "INTJ",
                            "languages": ["en"]
                        },
                    ]
            }
            
+ Response 200 (application/json)
    + Body
            {
                data: {
                    words: [
                        {
                            "dictionaryWord": "hello",
                            "partOfSpeechTag": "INTJ",
                            "languages": ["en"]
                        },
                    ]
                }
                "error": null,
                "meta": {
                    "entries": [{
                        "word": "hello"
                        "entries": [{ "start": 6, "end": 11 }]
                    }] 
                }
            }

# Dictionary [/dictionary]

## Get a dictionary from src [POST /dictionary/from-src]
Process text and return dictionary.

+ Request (application/json)

    + Body

            {
                "src": "Hello world"
            }

    + Schema

            {
                "type": "object",
                "properties": {
                    "src": { "type": "string" }
                },
                "additionalProperties": false
            }



+ Response 200 (application/json)

    + Body
            {
                data: {
                    words: [
                        {
                            "dictionaryWord": "hello",
                            "partOfSpeechTag": "INTJ",
                            "languages": ["en"]
                        },
                    ]
                }
                "error": null,
                "meta": {
                    "entries": [{
                        "word": "hello"
                        "entries": [{ "start": 6, "end": 11 }]
                    }] 
                }
            }
